#!/usr/bin/bash -ex
useradd -m -g users -G wheel,storage,power,lp,network,audio,video,optical -s /bin/bash awebber
sudo pacman -Sy rxvt-unicode curl wget git vim i3 i3blocks i3lock feh evince nemo file-roller networkmanager gthumb pulseaudio blueman arandr xfce4-power-manager pavucontrol compton pasystray rofi evolution nodejs npm yarn ttf-font-awesome docker python-pip cups ca-certificates ranger lxappearance gtk-chtheme networkmanager-dispatcher-ntpd cronie networkmanager network-manager-applet acpid cups avahi dbus udisks2 vlc chromium i3-gaps ttf-font-awesome awesome-terminal-fonts otf-font-awesome adobe-source-code-pro-fonts jsoncpp jgmenu dmenu rofi conky nitrogen dunst albert compton mate-power-manager adapta-gtk-theme papirus-icon-theme capitaine-cursors xorg xorg-xinit xorg-server networkmanager-openconnect bash-completion acpi tk go ebtables dnsmasq

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim
cp .* ~/ || true
cp -r .* ~/ || true
cd ~/projects && git clone https://github.com/powerline/powerline && cd powerline && sudo pip install .

