#!/usr/bin/bash -ex
# RUSTFLAGS=-Clinker=musl-gcc
sudo pacman -S rustup --noconfirm
rustup toolchain add stable
rustup toolchain add nightly
rustup target add wasm32-wasi
rustup target add wasm32-unknown-unknown
rustup target add x86_64-unknown-linux-musl
rustup component add rls rust-analysis rust-src clippy
sudo pacman -S rust-analyzer --noconfirm
cargo install cargo-edit
cargo install cargo-tarpaulin
cargo install cargo-expand
cargo install cargo-audit --features=fix
cargo install cargo-kcov
cargo install wasm-pack
mkdir -p ~/.local/bin || true
ln -s /bin/g++ ~/.local/bin/musl-g++
