#!/usr/bin/bash -ex
# RUSTFLAGS=-Clinker=musl-gcc
sudo pacman -S rustup --noconfirm
rustup toolchain add stable
rustup toolchain add nightly
rustup target add x86_64-unknown-linux-musl
rustup component add rls rust-analysis rust-src
cargo +nightly install racer
cargo install cargo-edit
cargo install cargo-audit
