#!/usr/bin/bash -ex
sudo apt install -y xorg xserver-xorg xinit rxvt-unicode curl wget git vim i3 i3blocks i3lock feh evince nemo file-roller gthumb xfce4-session pulseaudio blueman arandr xfce4-power-manager pavucontrol compton pasystray rofi evolution nodejs npm yarn docker python-pip cups ca-certificates ranger lxappearance gtk-chtheme libgconf-2-4 gnome-terminal openssh-server openssh-client ssh-askpass-gnome

curl -fLo ~/.vim/autoload/plug.vim --create-dirs \
    https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

wget https://github.com/authmane512/i3-config/raw/master/fontawesome.ttf
sudo mv fontawesome.ttf /usr/local/share/fonts/
xrdb ~/.Xresources

