#!/bin/sh
~/.local/bin/mutt_oauth2 \
    --client-id=536220415180-s2f65ora8pnpr78tqpcmssm2h8l952ra.apps.googleusercontent.com --client-secret=`pass console.google.com/credentials/neomutt/536220415180-s2f65ora8pnpr78tqpcmssm2h8l952ra.apps.googleusercontent.com` \
sign-in
