#!/usr/bin/bash -ex

yay pulseaudio-ctl
yay --nouseask --nocleanmenu --nodiffmenu oh-my-zsh-git <<< 1
yay obinskit
yay ublock
yay -R --useask --nocleanmenu --nodiffmenu vim <<< y
yay --nouseask --nocleanmenu --nodiffmenu neovim-symlinks <<< 1
ln -sf /usr/bin/nvim ~/.local/bin/vim
yay --nouseask --nocleanmenu --nodiffmenu eksctl <<< 1
yay --nouseask --nocleanmenu --nodiffmenu rancher-k3d-bin <<< 1
yay --nouseask --nocleanmenu --nodiffmenu gcalcli <<< 1
yay --nouseask --nocleanmenu --nodiffmenu typescript-language-server-bin <<< 1
# yay nerd-fonts-complete
