#!/usr/bin/bash -ex

yay pulseaudio-ctl
yay oh-my-zsh-git
yay obinskit
yay ublock
yay neovim-symlinks
yay gcalcli
yay --nouseask --nocleanmenu --nodiffmenu typescript-language-server-bin <<< 1
yay nerd-fonts-complete
