-- require('prettier').setup {
--     bin = 'prettierd',
--     filetypes = {
--         "css",
--         "javascript",
--         "javascriptreact",
--         "typescript",
--         "typescriptreact",
--         "json",
--         "scss",
--         "less"
--     }
-- }
