-- vim.opt.runtimepath:prepend("/home/awebber/.local/parsers")
-- require("nvim-treesitter.configs").setup({
-- 	parser_install_dir = "/home/awebber/.local/parsers",
-- 	auto_install = true,
-- 	sync_install = false,
-- 	highlight = {
-- 		enable = true,
-- 		disable = {},
-- 	},
-- 	indent = {
-- 		enable = true,
-- 		disable = {},
-- 	},
-- 	rainbow = {
-- 		enable = true,
-- 		extended_mode = true,
-- 		max_file_lines = nil,
-- 	},
-- 	ensure_installed = {
-- 		"tsx",
-- 		"typescript",
-- 		"javascript",
-- 		"markdown",
-- 		"markdown_inline",
-- 		"toml",
-- 		"json",
-- 		"yaml",
-- 		"html",
-- 		"rust",
-- 	},
-- 	autotag = {
-- 		enable = true,
-- 	},
-- })
-- local parser_config = require("nvim-treesitter.parsers").get_parser_configs()
-- parser_config.tsx.filetype_to_parsername = { "javascript", "typescript.tsx" }
