#!/bin/bash
chown -R $(whoami) ~/.gnupg/                                                                          (andrew@deepc.ai@knative.eu-central-1.eksctl.io/marketplace)
find ~/.gnupg -type f -exec chmod 600 {} \;                                                           (andrew@deepc.ai@knative.eu-central-1.eksctl.io/marketplace)
find ~/.gnupg -type d -exec chmod 700 {} \;
