#!/bin/bash
KCONTEXT=$(kubectl config current-context 2>/dev/null)
if [[ $?=="0" ]]; then
	CC=$(kubectl config view | grep current-context | awk '{print $2}')
	KNAMESPACE=$(kubectl config view  | grep namespace | awk '{print $2}')
    echo "☸ $CC/$KNAMESPACE ☸"
    echo "☸ $CC/$KNAMESPACE ☸"
    echo \#4040FF # color
fi

