#!/bin/sh
PASSWORD=`pass console.google.com/credentials/neomutt/536220415180-s2f65ora8pnpr78tqpcmssm2h8l952ra.apps.googleusercontent.com`
echo "📆 `/usr/bin/gcalcli --client-id 536220415180-s2f65ora8pnpr78tqpcmssm2h8l952ra.apps.googleusercontent.com --client-secret $PASSWORD --conky --nocolor --calenda "andrew@deepc.ai" agenda --nostarted | head -2 | tail -1 | awk '{$1=""; print $0}'`"
