abbr -a xclip "xclip -selection c"
abbr -a kgp "kubectl get pods"
abbr -a kgl "kubectl get logs"
abbr -a kdp "kubectl describe pod"
abbr -a kgd "kubectl get deploy"
abbr -a kgn "kubectl get nodes"
abbr -a mail-deepc 'neomutt -F ~/projects/i3/.mutt/neomuttrc_deepc'
abbr -a mail-gmail 'neomutt -F ~/projects/i3/.mutt/neomuttrc_me'
abbr -a mail-origins 'neomutt -F ~/projects/i3/.mutt/neomuttrc_origins'
