# Wayland and Platform
--ozone-platform-hint=auto
--enable-features=UseOzonePlatform,VaapiVideoDecoder,VaapiVideoEncoder,WebRTCPipeWireCapturer

# GPU and Acceleration (Allows WebGPU/WebGL)
--ignore-gpu-blocklist
--enable-gpu-rasterization
--enable-zero-copy
--enable-hardware-overlays
--enable-oop-rasterization
--enable-gpu-compositing

# UI
--force-dark-mode
--enable-features=WebUIDarkMode
